# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Inventory.create(:equipment_type => 'Audio', :equipment_name => 'Mackie SRM450v2 Powered Speaker', :num_of_items => '12', :rental_price => '200.00')
Inventory.create(:equipment_type => 'Audio', :equipment_name => 'Mackie SRM350v2 Powered Speaker', :num_of_items => '20', :rental_price => '125.00')
Inventory.create(:equipment_type => 'Audio', :equipment_name => 'Mackie SRM1801 18" Powered Subwoofer', :num_of_items => '6', :rental_price => '250.00')
Inventory.create(:equipment_type => 'Audio', :equipment_name => 'Speaker Stands TS-99BL', :num_of_items => '20', :rental_price => '20.00')
Inventory.create(:equipment_type => 'Audio', :equipment_name => 'JBL JRX115 Speaker', :num_of_items => '8', :rental_price => '150.00')
Inventory.create(:equipment_type => 'Audio', :equipment_name => 'JBL JRX112M Monitor Speaker', :num_of_items => '12', :rental_price => '85.00')
Inventory.create(:equipment_type => 'Audio', :equipment_name => 'JBL JRX118S Subwoofer', :num_of_items => '4', :rental_price => '125.00')
Inventory.create(:equipment_type => 'Audio', :equipment_name => 'Crown XTi 4002 Amplifier', :num_of_items => '8', :rental_price => '150.00')
Inventory.create(:equipment_type => 'Audio', :equipment_name => 'Crown XTi 2002 Amplifier', :num_of_items => '6', :rental_price => '125.00')
Inventory.create(:equipment_type => 'Audio', :equipment_name => 'Shure SM58 Microphone', :num_of_items => '20', :rental_price => '25.00')
Inventory.create(:equipment_type => 'Audio', :equipment_name => 'Shure SM57 Microphone', :num_of_items => '20', :rental_price => '25.00')
Inventory.create(:equipment_type => 'Audio', :equipment_name => 'Mic Stand - Boom', :num_of_items => '30', :rental_price => '20.00')
Inventory.create(:equipment_type => 'Audio', :equipment_name => 'Mic Stand - Straight', :num_of_items => '15', :rental_price => '15.00')
Inventory.create(:equipment_type => 'Audio', :equipment_name => 'Mic Stand - Instrument', :num_of_items => '20', :rental_price => '15.00')
Inventory.create(:equipment_type => 'Audio', :equipment_name => 'Shure Wireless Headset Mic', :num_of_items => '8', :rental_price => '150.00')
Inventory.create(:equipment_type => 'Audio', :equipment_name => 'Shure Wireless Handheld Mic', :num_of_items => '8', :rental_price => '130.00')
Inventory.create(:equipment_type => 'Audio', :equipment_name => 'Sennheiser Wireless Headset Mic', :num_of_items => '8', :rental_price => '120.00')
Inventory.create(:equipment_type => 'Audio', :equipment_name => 'Behringer X32 Digital Sound Board', :num_of_items => '2', :rental_price => '400.00')
Inventory.create(:equipment_type => 'Audio', :equipment_name => 'Allen and Heath MixWizard3 16:2 Sound Board', :num_of_items => '2', :rental_price => '175.00')
Inventory.create(:equipment_type => 'Audio', :equipment_name => 'Yamaha LS9 Digital Sound Board', :num_of_items => '1', :rental_price => '500.00')
Inventory.create(:equipment_type => 'Video', :equipment_name => '3000 Lumens Projector', :num_of_items => '4', :rental_price => '225.00')
Inventory.create(:equipment_type => 'Video', :equipment_name => '5000 Lumens Projector', :num_of_items => '4', :rental_price => '425.00')
Inventory.create(:equipment_type => 'Video', :equipment_name => '7800 Lumens Projector', :num_of_items => '3', :rental_price => '625.00')
Inventory.create(:equipment_type => 'Video', :equipment_name => '10000 Lumens Projector', :num_of_items => '2', :rental_price => '900.00')
Inventory.create(:equipment_type => 'Video', :equipment_name => 'Widescreen Projector Screen - 8ft x 14ft RP', :num_of_items => '6', :rental_price => '300.00')
Inventory.create(:equipment_type => 'Video', :equipment_name => 'Widescreen Projector Screen - 9ft x 16ft RP', :num_of_items => '4', :rental_price => '375.00')
Inventory.create(:equipment_type => 'Video', :equipment_name => 'Widescreen Projector Screen - 7ft x 12ft RP', :num_of_items => '4', :rental_price => '225.00')
Inventory.create(:equipment_type => 'Video', :equipment_name => 'Widescreen Projector Screen - 8ft x 14ft', :num_of_items => '6', :rental_price => '300.00')
Inventory.create(:equipment_type => 'Video', :equipment_name => 'Widescreen Projector Screen - 9ft x 16ft', :num_of_items => '4', :rental_price => '375.00')
Inventory.create(:equipment_type => 'Video', :equipment_name => 'Widescreen Projector Screen - 7ft x 12ft', :num_of_items => '4', :rental_price => '225.00')
Inventory.create(:equipment_type => 'Video', :equipment_name => 'JVC HM-600U Digital Video Camcorder', :num_of_items => '10', :rental_price => '450.00')
Inventory.create(:equipment_type => 'Video', :equipment_name => 'JVC HM-650U Digital Video Camcorder', :num_of_items => '4', :rental_price => '550.00')
Inventory.create(:equipment_type => 'Video', :equipment_name => 'Libec LX7 Camera Tripod', :num_of_items => '6', :rental_price => '75.00')
Inventory.create(:equipment_type => 'Video', :equipment_name => '42in Television', :num_of_items => '4', :rental_price => '400.00')
Inventory.create(:equipment_type => 'Video', :equipment_name => '60in Television', :num_of_items => '4', :rental_price => '600.00')
Inventory.create(:equipment_type => 'Video', :equipment_name => 'Blackmagic ATEM 2 M/E Production Switcher', :num_of_items => '1', :rental_price => '500.00')
Inventory.create(:equipment_type => 'Video', :equipment_name => 'Blackmagic Television Studio', :num_of_items => '2', :rental_price => '200.00')
Inventory.create(:equipment_type => 'Video', :equipment_name => 'Blackmagic ATEM 2 M/E Broadcast Panel', :num_of_items => '1', :rental_price => '600.00')
Inventory.create(:equipment_type => 'Video', :equipment_name => 'Blackmagic ATEM 1 M/E Broadcast Panel', :num_of_items => '1', :rental_price => '300.00')
Inventory.create(:equipment_type => 'Video', :equipment_name => '15in MacBook Pro with Video Editing Software', :num_of_items => '2', :rental_price => '275.00')
Inventory.create(:equipment_type => 'Lighting', :equipment_name => 'ETC ParNEL lights', :num_of_items => '36', :rental_price => '30.00')
Inventory.create(:equipment_type => 'Lighting', :equipment_name => 'ETC Par lights', :num_of_items => '24', :rental_price => '20.00')
Inventory.create(:equipment_type => 'Lighting', :equipment_name => 'ETC SourceFour 19 degree Leko', :num_of_items => '28', :rental_price => '35.00')
Inventory.create(:equipment_type => 'Lighting', :equipment_name => 'ETC SourceFour 26 degree Leko', :num_of_items => '18', :rental_price => '35.00')
Inventory.create(:equipment_type => 'Lighting', :equipment_name => 'ETC SourceFour 36 degree Leko', :num_of_items => '18', :rental_price => '35.00')
Inventory.create(:equipment_type => 'Lighting', :equipment_name => 'ETC SourceFour LED Leko', :num_of_items => '18', :rental_price => '55.00')
Inventory.create(:equipment_type => 'Lighting', :equipment_name => 'Elation Opti QA Par LED', :num_of_items => '24', :rental_price => '75.00')
Inventory.create(:equipment_type => 'Lighting', :equipment_name => 'ETC D60 LED', :num_of_items => '12', :rental_price => '150.00')
Inventory.create(:equipment_type => 'Lighting', :equipment_name => 'Robe ColorSpot 575 AT Moving Light', :num_of_items => '8', :rental_price => '250.00')
Inventory.create(:equipment_type => 'Lighting', :equipment_name => '10ft Truss', :num_of_items => '50', :rental_price => '35.00')
Inventory.create(:equipment_type => 'Lighting', :equipment_name => '5ft Truss', :num_of_items => '25', :rental_price => '25.00')
Inventory.create(:equipment_type => 'Lighting', :equipment_name => 'ST20 Lifts', :num_of_items => '10', :rental_price => '100.00')
Inventory.create(:equipment_type => 'Lighting', :equipment_name => '20 amp Dimmer Pack', :num_of_items => '15', :rental_price => '30.00')
Inventory.create(:equipment_type => 'Lighting', :equipment_name => '40 amp Dimmer Pack', :num_of_items => '25', :rental_price => '45.00')
Inventory.create(:equipment_type => 'Lighting', :equipment_name => '100 amp Dimmer Rack', :num_of_items => '5', :rental_price => '150.00')
Inventory.create(:equipment_type => 'Lighting', :equipment_name => 'Leprecon 624 Light Board', :num_of_items => '4', :rental_price => '120.00')
Inventory.create(:equipment_type => 'Lighting', :equipment_name => 'High End Hog4 Lighting Console', :num_of_items => '1', :rental_price => '375.00')
Inventory.create(:equipment_type => 'Lighting', :equipment_name => 'High End Road Hog4 Lighting Console', :num_of_items => '2', :rental_price => '235.00')
Inventory.create(:equipment_type => 'Lighting', :equipment_name => 'Elation DMX Operator Light Board', :num_of_items => '2', :rental_price => '85.00')
Inventory.create(:equipment_type => 'Lighting', :equipment_name => 'Power Distro', :num_of_items => '3', :rental_price => '140.00')
Inventory.create(:equipment_type => 'Misc', :equipment_name => 'Audio Cable Package - Small', :num_of_items => '4', :rental_price => '25.00')
Inventory.create(:equipment_type => 'Misc', :equipment_name => 'Audio Cable Package - Medium', :num_of_items => '6', :rental_price => '45.00')
Inventory.create(:equipment_type => 'Misc', :equipment_name => 'Audio Cable Package - Large', :num_of_items => '4', :rental_price => '75.00')
Inventory.create(:equipment_type => 'Misc', :equipment_name => 'Audio Cable Package - Extra Large', :num_of_items => '2', :rental_price => '130.00')
Inventory.create(:equipment_type => 'Misc', :equipment_name => 'Camera Cable Package - Small', :num_of_items => '2', :rental_price => '25.00')
Inventory.create(:equipment_type => 'Misc', :equipment_name => 'Camera Cable Package - Large', :num_of_items => '2', :rental_price => '50.00')
Inventory.create(:equipment_type => 'Misc', :equipment_name => 'VGA Projector Cable Package - Small', :num_of_items => '6', :rental_price => '30.00')
Inventory.create(:equipment_type => 'Misc', :equipment_name => 'VGA Projector Cable Package - Large', :num_of_items => '4', :rental_price => '60.00')
Inventory.create(:equipment_type => 'Misc', :equipment_name => 'HDMI Projector Cable Package', :num_of_items => '6', :rental_price => '100.00')
Inventory.create(:equipment_type => 'Misc', :equipment_name => 'Power Cable Package - Small', :num_of_items => '8', :rental_price => '25.00')
Inventory.create(:equipment_type => 'Misc', :equipment_name => 'Power Cable Package - Medium', :num_of_items => '8', :rental_price => '40.00')
Inventory.create(:equipment_type => 'Misc', :equipment_name => 'Power Cable Package - Large', :num_of_items => '6', :rental_price => '70.00')
Inventory.create(:equipment_type => 'Misc', :equipment_name => 'Power Cable Package - Extra Large', :num_of_items => '2', :rental_price => '150.00')
Inventory.create(:equipment_type => 'Misc', :equipment_name => 'SOCO Cable Package - Small', :num_of_items => '4', :rental_price => '50.00')
Inventory.create(:equipment_type => 'Misc', :equipment_name => 'SOCO Cable Package - Medium', :num_of_items => '8', :rental_price => '200.00')
Inventory.create(:equipment_type => 'Misc', :equipment_name => 'SOCO Cable Package - Large', :num_of_items => '8', :rental_price => '350.00')
Inventory.create(:equipment_type => 'Misc', :equipment_name => 'Power Distro Cable Package', :num_of_items => '3', :rental_price => '140.00')
Inventory.create(:equipment_type => 'Misc', :equipment_name => '5 Person Single Channel COM System', :num_of_items => '4', :rental_price => '250.00')
Inventory.create(:equipment_type => 'Misc', :equipment_name => '8 Person Dual Channel COM System', :num_of_items => '4', :rental_price => '500.00')
Inventory.create(:equipment_type => 'Misc', :equipment_name => '10+ Person Dual Channel COM System', :num_of_items => '2', :rental_price => '1000.00')
